; =============================================================================
;  RC CAR — RECEIVER
;  Desteklenen platformlar: ESP8266, ESP32
;  Desteklenen input kaynakları: ESP-NOW, Android UDP, PS3, PS4
; =============================================================================

[platformio]
; nodemcuv2 / esp32_nops / esp32_ps3 / esp32_ps4
default_envs = esp32_nops

; =============================================================================
;  Ortak ayarlar (tüm env'ler bu bölümü miras alır)
; =============================================================================
[env_base]
monitor_speed = 115200
port = com3;
lib_deps = 
	bblanchon/ArduinoJson
    fanfanlatulipe26/FS_MX1508@^1.1.0

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_port = ${env_base.port}
monitor_port = ${env_base.port}
monitor_speed = ${env_base.monitor_speed}
lib_deps = 
	${env_base.lib_deps}
build_flags = -DBOARD_TYPE=1

[env:esp32_nops]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = ${env_base.port}
monitor_port = ${env_base.port}
monitor_speed = ${env_base.monitor_speed}
lib_deps = 
	${env_base.lib_deps}
	madhephaestus/ESP32Servo
build_flags = -DBOARD_TYPE=2 -DRX_INPUT_SOURCE=1

[env:esp32_ps3]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = ${env_base.port}
monitor_port = ${env_base.port}
monitor_speed = ${env_base.monitor_speed}
lib_deps = 
	${env_base.lib_deps}
	madhephaestus/ESP32Servo
	jvpernis/PS3 Controller Host @ ^1.1.0
build_flags = -DBOARD_TYPE=2 -DRX_INPUT_SOURCE=2

[env:esp32_ps4]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = ${env_base.port}
monitor_port = ${env_base.port}
monitor_speed = ${env_base.monitor_speed}
lib_deps = 
	${env_base.lib_deps}
	madhephaestus/ESP32Servo
	pablomarquez76/PS4_Controller_Host @ ^1.1.1
build_flags = -DBOARD_TYPE=2 -DRX_INPUT_SOURCE=3
